// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Frame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("Data.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FrameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrameId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4deb0123-af83-43f9-b0eb-0d073b92c8cc"),
                            Name = "Wood",
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("6b57748c-e193-4fe5-9553-c8d557e4336b"),
                            Name = "Iron",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("95ba9ece-f754-4cd7-9452-2a267b8f682e"),
                            Name = "Black paint",
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("14c9eeb1-80c7-400f-bd21-3567c379934b"),
                            Name = "Yellow paint",
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Data.Models.Material", b =>
                {
                    b.HasOne("Data.Models.Frame", null)
                        .WithMany("Materials")
                        .HasForeignKey("FrameId");
                });
#pragma warning restore 612, 618
        }
    }
}
